# Generated by Django 3.0.7 on 2020-10-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inreachmessage',
            name='message',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='inreachmessage',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
