# Generated by Django 3.0.7 on 2020-10-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0002_auto_20201003_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inreachmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
