# Generated by Django 3.1.2 on 2020-10-04 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_parser', '0003_auto_20201003_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=60)),
                ('loc_lat', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('loc_lng', models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
