# Generated by Django 3.1.2 on 2020-10-04 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_parser', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inreachmessage',
            name='mapshare',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='inreachmessage',
            name='original',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='inreachmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
