# Generated by Django 3.1.2 on 2020-10-07 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_parser', '0005_auto_20201004_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Trip', max_length=60)),
                ('departs', models.DateTimeField()),
                ('returns', models.DateTimeField()),
                ('overdue', models.DateTimeField(null=True)),
                ('description', models.TextField(default='None')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
