# Generated by Django 3.1.2 on 2020-10-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0008_trip_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='points',
            field=models.TextField(default=''),
        ),
    ]
