# Generated by Django 3.1.2 on 2020-10-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0009_trip_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inreachmessage',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-departs']},
        ),
    ]
