# Generated by Django 3.1.2 on 2020-10-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0010_auto_20201008_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='paths',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='points',
            field=models.TextField(default='[]'),
        ),
    ]
