# Generated by Django 3.1.2 on 2020-10-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0011_auto_20201009_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(default='None', null=True),
        ),
    ]
