# Generated by Django 3.1.2 on 2020-10-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0014_auto_20201009_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
