# Generated by Django 3.1.2 on 2021-01-11 20:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0015_auto_20201009_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
