# Generated by Django 3.1.2 on 2021-01-11 20:06

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Trips = apps.get_model('mail_parser', 'Trip')
    for row in Trips.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0016_trip_uuid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
