# Generated by Django 3.1.2 on 2021-01-11 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0017_auto_20210111_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
