# Generated by Django 3.1.2 on 2021-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0018_auto_20210111_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pass_phrase',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
