# Generated by Django 3.1.2 on 2021-01-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0020_auto_20210130_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='trips', to='mail_parser.Contact'),
        ),
    ]
