# Generated by Django 3.1.2 on 2021-01-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0021_trip_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
