# Generated by Django 3.1.2 on 2021-01-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0022_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='relationship',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
