# Generated by Django 3.2.4 on 2021-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0023_auto_20210131_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mapshape_ID',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
