# Generated by Django 3.2.4 on 2021-06-19 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0024_profile_mapshape_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mapshape_ID',
            new_name='mapshare_ID',
        ),
    ]
