# Generated by Django 3.2.4 on 2021-11-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0025_rename_mapshape_id_profile_mapshare_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InReachMessage',
        ),
    ]
