# Generated by Django 3.2.4 on 2021-11-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_parser', '0026_delete_inreachmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
